services:
  #DockerFileからAPPコンテナ起動
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.mysql
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    env_file:
        - .env.mysql
    #healthCheckを追加
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 10s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local

