services:
  #DockerFileからAPPコンテナ起動
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.app
    env_file:
      - ./app/.env.mysql
    volumes:
      - ./app/target:/app/target
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile.mysql
    env_file:
        - ./mysql/.env.mysql
    #healthCheckを追加
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 10s
      retries: 5
    volumes:
#      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - backend

#nginx
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - backend

volumes:
  mysql_data:
    driver: local

networks:
  backend:
    driver: bridge
